name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'feature-request', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! We appreciate your input and will carefully consider your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature in detail...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: A clear and concise description of any alternative solutions or features you've considered...
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - User Interface (UI)
        - User Experience (UX)
        - Educational Content
        - Assessment/Quiz System
        - Navigation
        - Accessibility
        - Performance
        - Admin Features
        - API/Integration
        - Mobile Experience
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve the experience
        - High - Significant impact on usability
        - Critical - Blocking current workflow
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature
      placeholder: |
        As a [type of user], I want [some goal] so that [some reason].
        
        Example:
        As a student, I want to bookmark lessons so that I can easily return to important content later.
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: mockups-wireframes
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or visual examples
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects or constraints to consider?
      placeholder: |
        - Data storage requirements
        - Performance implications
        - Browser compatibility
        - Mobile considerations
        - etc.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that would be helpful...
    validations:
      required: false

  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Have you done any research on this feature?
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
        - label: I have checked the documentation to see if this feature already exists
        - label: I have considered the impact this feature might have on existing functionality
        - label: I am willing to help test this feature when it's implemented

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained the problem this feature would solve
          required: true
        - label: I understand that feature requests are evaluated based on various factors including complexity, user benefit, and project goals
          required: true