import { Page } from '@playwright/test';
import { BasePage } from '../utils/test-helpers';
export declare class ModulePage extends BasePage {
    constructor(page: Page);
    get moduleTitle(): import("playwright-core").Locator;
    get moduleContent(): import("playwright-core").Locator;
    get sectionContent(): import("playwright-core").Locator;
    get progressBar(): import("playwright-core").Locator;
    get nextButton(): import("playwright-core").Locator;
    get previousButton(): import("playwright-core").Locator;
    get startButton(): import("playwright-core").Locator;
    get completeButton(): import("playwright-core").Locator;
    get tableOfContents(): import("playwright-core").Locator;
    get sectionList(): import("playwright-core").Locator;
    get notesButton(): import("playwright-core").Locator;
    get notesPanel(): import("playwright-core").Locator;
    get noteInput(): import("playwright-core").Locator;
    get saveNoteButton(): import("playwright-core").Locator;
    get videoPlayer(): import("playwright-core").Locator;
    get playButton(): import("playwright-core").Locator;
    get subtitleButton(): import("playwright-core").Locator;
    get quizSection(): import("playwright-core").Locator;
    get timeSpentDisplay(): import("playwright-core").Locator;
    navigateToModule(moduleId: number): Promise<void>;
    navigateToSection(moduleId: number, sectionId: number): Promise<void>;
    startModule(): Promise<void>;
    nextSection(): Promise<void>;
    previousSection(): Promise<void>;
    markSectionComplete(): Promise<void>;
    openTableOfContents(): Promise<void>;
    jumpToSection(sectionIndex: number): Promise<void>;
    openNotes(): Promise<void>;
    addNote(noteContent: string): Promise<void>;
    playVideo(): Promise<void>;
    toggleSubtitles(): Promise<void>;
    scrollThroughContent(): Promise<void>;
    simulateReadingTime(seconds?: number): Promise<void>;
    expectModuleLoaded(expectedTitle?: string): Promise<void>;
    expectContentVisible(): Promise<void>;
    expectProgressUpdated(): Promise<void>;
    expectSectionCompleted(): Promise<void>;
    expectNavigationAvailable(): Promise<void>;
    expectVideoPlayerLoaded(): Promise<void>;
    expectNotesAvailable(): Promise<void>;
    expectNoteAdded(noteContent: string): Promise<void>;
    expectQuizAvailable(): Promise<void>;
    expectTimeTracked(): Promise<void>;
    expectAccessibleContent(): Promise<void>;
}
//# sourceMappingURL=ModulePage.d.ts.map