import { Page } from '@playwright/test';
import { BasePage } from '../utils/test-helpers';
export declare class QuizPage extends BasePage {
    constructor(page: Page);
    get quizTitle(): import("playwright-core").Locator;
    get instructions(): import("playwright-core").Locator;
    get startButton(): import("playwright-core").Locator;
    get questionText(): import("playwright-core").Locator;
    get questionOptions(): import("playwright-core").Locator;
    get nextButton(): import("playwright-core").Locator;
    get previousButton(): import("playwright-core").Locator;
    get submitButton(): import("playwright-core").Locator;
    get timer(): import("playwright-core").Locator;
    get progressIndicator(): import("playwright-core").Locator;
    get results(): import("playwright-core").Locator;
    get scoreDisplay(): import("playwright-core").Locator;
    get passStatus(): import("playwright-core").Locator;
    get feedback(): import("playwright-core").Locator;
    get reviewButton(): import("playwright-core").Locator;
    get truefalseOptions(): import("playwright-core").Locator;
    get fillBlankInput(): import("playwright-core").Locator;
    get essayInput(): import("playwright-core").Locator;
    get wordCount(): import("playwright-core").Locator;
    get resumeButton(): import("playwright-core").Locator;
    get recommendationsSection(): import("playwright-core").Locator;
    navigateToQuiz(quizId: number): Promise<void>;
    startQuiz(): Promise<void>;
    answerMultipleChoice(optionIndex: number): Promise<void>;
    answerTrueFalse(isTrue: boolean): Promise<void>;
    answerFillBlank(answer: string): Promise<void>;
    answerEssay(answer: string): Promise<void>;
    nextQuestion(): Promise<void>;
    previousQuestion(): Promise<void>;
    submitQuiz(): Promise<void>;
    resumeQuiz(): Promise<void>;
    reviewAnswers(): Promise<void>;
    completeMultipleChoiceQuiz(answers: number[]): Promise<void>;
    completeMixedQuiz(answers: {
        type: 'multiple_choice' | 'true_false' | 'fill_blank' | 'essay';
        answer: number | boolean | string;
    }[]): Promise<void>;
    expectQuizLoaded(expectedTitle?: string): Promise<void>;
    expectQuizStarted(): Promise<void>;
    expectTimerVisible(): Promise<void>;
    expectQuestionVisible(questionText?: string): Promise<void>;
    expectOptionsAvailable(expectedCount?: number): Promise<void>;
    expectAnswerSelected(): Promise<void>;
    expectResultsDisplayed(): Promise<void>;
    expectScore(expectedScore: number | string): Promise<void>;
    expectPassStatus(shouldPass: boolean): Promise<void>;
    expectFeedback(feedbackText?: string): Promise<void>;
    expectResumeOption(): Promise<void>;
    expectProgressIndicator(): Promise<void>;
    expectWordCountTracking(): Promise<void>;
    expectRecommendations(): Promise<void>;
    expectQuizReviewAvailable(): Promise<void>;
    expectCorrectAnswerHighlighted(): Promise<void>;
    expectIncorrectAnswerHighlighted(): Promise<void>;
    expectExplanationVisible(): Promise<void>;
    expectMobileQuizLayout(): Promise<void>;
    expectTouchFriendlyOptions(): Promise<void>;
}
//# sourceMappingURL=QuizPage.d.ts.map